/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Visao;

import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

import Controle.LaboratorioDAO;
import Modelo.Laboratorio;
import java.util.Date;
import java.util.TimeZone;

/**
 *
 * @author Tem
 */
public class RegistarLaboratorio extends javax.swing.JFrame {

    /**
     * Creates new form
     */
    public RegistarLaboratorio() {

        initComponents();
        readJTable();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        buttonGroup3 = new javax.swing.ButtonGroup();
        buttonGroup4 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        lblRegistoLaboratorio = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        lblNrlaboratorio = new javax.swing.JLabel();
        lblComponentesInformaticos = new javax.swing.JLabel();
        jtfNumeroLaboratorio = new javax.swing.JTextField();
        jtfComponentesInformaticos = new javax.swing.JTextField();
        jPanel6 = new javax.swing.JPanel();
        lblComponentesNaoInfor = new javax.swing.JLabel();
        jtfComponentesNaoInformaticos = new javax.swing.JTextField();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tabela = new javax.swing.JTable();
        jPanel4 = new javax.swing.JPanel();
        jbtGravar = new javax.swing.JButton();
        jbtActualizar = new javax.swing.JButton();
        jbtRemover = new javax.swing.JButton();
        jbrPesquisar = new javax.swing.JButton();
        jbtLimpar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        lblRegistoLaboratorio.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        lblRegistoLaboratorio.setText("REGISTO DO LABORATORIO");
        jPanel1.add(lblRegistoLaboratorio);

        jPanel5.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                jPanel5AncestorAdded(evt);
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });

        lblNrlaboratorio.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        lblNrlaboratorio.setText("Numero Laboratorio");

        lblComponentesInformaticos.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        lblComponentesInformaticos.setText("Componentes Informat.");

        jtfNumeroLaboratorio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtfNumeroLaboratorioActionPerformed(evt);
            }
        });
        jtfNumeroLaboratorio.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                jtfNumeroLaboratorioPropertyChange(evt);
            }
        });
        jtfNumeroLaboratorio.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jtfNumeroLaboratorioKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jtfNumeroLaboratorioKeyTyped(evt);
            }
        });

        jtfComponentesInformaticos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtfComponentesInformaticosActionPerformed(evt);
            }
        });
        jtfComponentesInformaticos.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jtfComponentesInformaticosKeyPressed(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblNrlaboratorio, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblComponentesInformaticos, javax.swing.GroupLayout.PREFERRED_SIZE, 192, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jtfComponentesInformaticos, javax.swing.GroupLayout.DEFAULT_SIZE, 218, Short.MAX_VALUE)
                    .addComponent(jtfNumeroLaboratorio))
                .addGap(107, 107, 107))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblNrlaboratorio)
                    .addComponent(jtfNumeroLaboratorio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 42, Short.MAX_VALUE)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblComponentesInformaticos)
                    .addComponent(jtfComponentesInformaticos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(75, 75, 75))
        );

        jPanel6.setLayout(null);

        lblComponentesNaoInfor.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        lblComponentesNaoInfor.setText("Componentes nao Informat.");
        jPanel6.add(lblComponentesNaoInfor);
        lblComponentesNaoInfor.setBounds(50, 10, 230, 22);

        jtfComponentesNaoInformaticos.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jtfComponentesNaoInformaticosKeyPressed(evt);
            }
        });
        jPanel6.add(jtfComponentesNaoInformaticos);
        jtfComponentesNaoInformaticos.setBounds(300, 10, 190, 30);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, 512, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 13, Short.MAX_VALUE))
            .addComponent(jPanel6, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jPanel3.setLayout(new java.awt.BorderLayout());

        tabela.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Numero Laboratorio", "Componentes Informaticos", "Componentes Nao Informaticos", "Data"
            }
        ));
        tabela.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                tabelaAncestorAdded(evt);
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });
        tabela.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabelaMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tabela);

        jPanel3.add(jScrollPane2, java.awt.BorderLayout.CENTER);

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));

        jbtGravar.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jbtGravar.setText("Gravar");
        jbtGravar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtGravarActionPerformed(evt);
            }
        });
        jbtGravar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jbtGravarKeyPressed(evt);
            }
        });
        jPanel4.add(jbtGravar);

        jbtActualizar.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jbtActualizar.setText("Actualizar");
        jbtActualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtActualizarActionPerformed(evt);
            }
        });
        jPanel4.add(jbtActualizar);

        jbtRemover.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jbtRemover.setText("Remover");
        jbtRemover.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtRemoverActionPerformed(evt);
            }
        });
        jPanel4.add(jbtRemover);

        jbrPesquisar.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jbrPesquisar.setText("Pesquisar");
        jbrPesquisar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbrPesquisarActionPerformed(evt);
            }
        });
        jPanel4.add(jbrPesquisar);

        jbtLimpar.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jbtLimpar.setText("Limpar");
        jbtLimpar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtLimparActionPerformed(evt);
            }
        });
        jPanel4.add(jbtLimpar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, 191, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents


    private void jbtLimparActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtLimparActionPerformed
        // TODO add your handling code here:

        jtfNumeroLaboratorio.setText(null);
        jtfComponentesInformaticos.setText(null);
        jtfComponentesNaoInformaticos.setText(null);
        readJTable();
    }//GEN-LAST:event_jbtLimparActionPerformed

    private void tabelaAncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_tabelaAncestorAdded
        // TODO add your handling code here:
    }//GEN-LAST:event_tabelaAncestorAdded

    private void jbtGravarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtGravarActionPerformed
        // TODO add your handling code here:
        Laboratorio a = new Laboratorio();

        LaboratorioDAO estu = new LaboratorioDAO();

        a.setNumerolaboratorio(jtfNumeroLaboratorio.getText());
        a.setComponentesinformaticos(jtfComponentesInformaticos.getText());
        a.setComponentesnaoinformaticos(jtfComponentesNaoInformaticos.getText());
        a.setData(new Date());

        if (estu.gravar(a)) {
            JOptionPane.showMessageDialog(null, "O laboratorio foi registado com sucesso");
            jtfNumeroLaboratorio.setText(null);
            jtfComponentesInformaticos.setText(null);
            jtfComponentesNaoInformaticos.setText(null);
        } else {
            JOptionPane.showMessageDialog(null, "O laboratorio nao foi  registado com sucesso");
        }

        readJTable();
    }//GEN-LAST:event_jbtGravarActionPerformed

    private void jbtActualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtActualizarActionPerformed
        // TODO add your handling code here:
        if (tabela.getSelectedRow() != -1) {
            Laboratorio a = new Laboratorio();

            LaboratorioDAO estu = new LaboratorioDAO();

            a.setNumerolaboratorio(jtfNumeroLaboratorio.getText());
            a.setComponentesinformaticos(jtfComponentesInformaticos.getText());
            a.setComponentesnaoinformaticos(jtfComponentesNaoInformaticos.getText());
            a.setData((Date) tabela.getValueAt(tabela.getSelectedRow(), 3));

            if (estu.atualizar(a)) {
                JOptionPane.showMessageDialog(null, "O laboratorio foi actualizado com sucesso");
            } else {
                JOptionPane.showMessageDialog(null, "O laboratorio nao foi actualizado!!!");
            }

            jtfNumeroLaboratorio.setText(null);
            jtfComponentesInformaticos.setText(null);
            jtfComponentesNaoInformaticos.setText(null);
            readJTable();

        }
    }//GEN-LAST:event_jbtActualizarActionPerformed

    private void jbtRemoverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtRemoverActionPerformed
        // TODO add your handling code here:
        if (tabela.getSelectedRow() != -1) {
            Laboratorio a = new Laboratorio();
            LaboratorioDAO dau = new LaboratorioDAO();

            String d = tabela.getValueAt(tabela.getSelectedRow(), 0)
                    .toString();
            a.setNumerolaboratorio(d);
            dau.remover(a);

            JOptionPane.showMessageDialog(null,
                    "Removido com sucesso");
            readJTable();

        } else {
            JOptionPane.showMessageDialog(null,
                    "Selecione um laboratorio para poder remover");
        }

    }//GEN-LAST:event_jbtRemoverActionPerformed

    private void jbrPesquisarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbrPesquisarActionPerformed
        // TODO add your handling code here:
        readJTable1();
    }//GEN-LAST:event_jbrPesquisarActionPerformed

    private void tabelaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabelaMouseClicked
        // TODO add your handling code here:
        if (tabela.getSelectedRow() != -1) {
            jtfNumeroLaboratorio.setText(tabela.getValueAt(tabela.getSelectedRow(), 0).toString());
            jtfComponentesInformaticos.setText(tabela.getValueAt(tabela.getSelectedRow(), 1).toString());
            jtfComponentesNaoInformaticos.setText(tabela.getValueAt(tabela.getSelectedRow(), 2).toString());

        }
    }//GEN-LAST:event_tabelaMouseClicked

    private void jPanel5AncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_jPanel5AncestorAdded
        // TODO add your handling code here:
    }//GEN-LAST:event_jPanel5AncestorAdded

    private void jtfNumeroLaboratorioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtfNumeroLaboratorioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtfNumeroLaboratorioActionPerformed

    private void jtfComponentesInformaticosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtfComponentesInformaticosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtfComponentesInformaticosActionPerformed

    private void jtfNumeroLaboratorioKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtfNumeroLaboratorioKeyPressed

        if (evt.getKeyCode() == evt.VK_ENTER) {
            jtfComponentesInformaticos.requestFocus();
        }
    }//GEN-LAST:event_jtfNumeroLaboratorioKeyPressed

    private void jtfComponentesInformaticosKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtfComponentesInformaticosKeyPressed

        // TODO add your handling code here:
        if (evt.getKeyCode() == evt.VK_ENTER) {
            jtfComponentesNaoInformaticos.requestFocus();
        }
    }//GEN-LAST:event_jtfComponentesInformaticosKeyPressed

    private void jbtGravarKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jbtGravarKeyPressed
        // TODO add your handling code here:

    }//GEN-LAST:event_jbtGravarKeyPressed

    private void jtfNumeroLaboratorioKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtfNumeroLaboratorioKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_jtfNumeroLaboratorioKeyTyped

    private void jtfNumeroLaboratorioPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_jtfNumeroLaboratorioPropertyChange
        // TODO add your handling code here:
    }//GEN-LAST:event_jtfNumeroLaboratorioPropertyChange

    private void jtfComponentesNaoInformaticosKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtfComponentesNaoInformaticosKeyPressed
        // TODO add your handling code here:
        if (evt.getKeyCode() == evt.VK_ENTER) {
            jbtGravar.requestFocus();
        }
    }//GEN-LAST:event_jtfComponentesNaoInformaticosKeyPressed

    public void readJTable() {
        DefaultTableModel modelo1 = (DefaultTableModel) tabela.getModel();
        modelo1.setNumRows(0);
        LaboratorioDAO dau = new LaboratorioDAO();

        for (Laboratorio a : dau.consular()) {

            modelo1.addRow(new Object[]{a.getNumerolaboratorio(), a.getComponentesinformaticos(),
                a.getComponentesnaoinformaticos(), a.getData()

            });

        }
    }

    public void readJTable1() {
        DefaultTableModel modelo1 = (DefaultTableModel) tabela.getModel();
        modelo1.setNumRows(0);
        LaboratorioDAO dau = new LaboratorioDAO();

        for (Laboratorio a : dau.consular()) {
            if (a.getNumerolaboratorio().equalsIgnoreCase(jtfNumeroLaboratorio.getText())) {

                modelo1.addRow(new Object[]{a.getNumerolaboratorio(), a.getComponentesinformaticos(),
                    a.getComponentesnaoinformaticos(), a.getData()

                });
            }
        }
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;

                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(RegistarLaboratorio.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(RegistarLaboratorio.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(RegistarLaboratorio.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(RegistarLaboratorio.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new RegistarLaboratorio().setVisible(true);

            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.ButtonGroup buttonGroup3;
    private javax.swing.ButtonGroup buttonGroup4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JButton jbrPesquisar;
    private javax.swing.JButton jbtActualizar;
    private javax.swing.JButton jbtGravar;
    private javax.swing.JButton jbtLimpar;
    private javax.swing.JButton jbtRemover;
    private javax.swing.JTextField jtfComponentesInformaticos;
    private javax.swing.JTextField jtfComponentesNaoInformaticos;
    private javax.swing.JTextField jtfNumeroLaboratorio;
    private javax.swing.JLabel lblComponentesInformaticos;
    private javax.swing.JLabel lblComponentesNaoInfor;
    private javax.swing.JLabel lblNrlaboratorio;
    private javax.swing.JLabel lblRegistoLaboratorio;
    private javax.swing.JTable tabela;
    // End of variables declaration//GEN-END:variables
}
