/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Visao;

import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

import Controle.RequisitarMaterialDAO;
import Controle.FuncionarioDAO;
import Controle.EstudanteDAO;
import Modelo.RequisitarMaterial;
import Modelo.Estudante;
import Modelo.Funcionario;
import Modelo.Material;
import java.util.Date;
import java.util.TimeZone;

/**
 *
 * @author Tem
 */
public class TelaRequisitarMaterial extends javax.swing.JFrame {

    /**
     * Creates new form
     */
    public TelaRequisitarMaterial() {

        initComponents();
        readJTable();
        adcionarEstudante();
        adcionarFuncionario();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        lblRequisitarMaterial = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        lblNomeEstudantes = new javax.swing.JLabel();
        lblCodigoMaterial = new javax.swing.JLabel();
        jtfCodigoMaterial = new javax.swing.JTextField();
        jcbNomeEstudantes = new javax.swing.JComboBox<>();
        jPanel6 = new javax.swing.JPanel();
        jcbNomeFuncionarios = new javax.swing.JComboBox<>();
        lblNomeFuncionarios = new javax.swing.JLabel();
        lblMaterialRequisitado = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tabela = new javax.swing.JTable();
        jPanel4 = new javax.swing.JPanel();
        jbtGravar = new javax.swing.JButton();
        jbtActualizar = new javax.swing.JButton();
        jbtRemover = new javax.swing.JButton();
        jbrPesquisar = new javax.swing.JButton();
        jbtLimpar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        lblRequisitarMaterial.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        lblRequisitarMaterial.setText("REQUISITTAR MATERIAL");
        jPanel1.add(lblRequisitarMaterial);

        jPanel5.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                jPanel5AncestorAdded(evt);
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });

        lblNomeEstudantes.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        lblNomeEstudantes.setText("Nome Est.");
        lblNomeEstudantes.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                lblNomeEstudantesKeyPressed(evt);
            }
        });

        lblCodigoMaterial.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        lblCodigoMaterial.setText("Codigo Mat.");

        jtfCodigoMaterial.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtfCodigoMaterialActionPerformed(evt);
            }
        });
        jtfCodigoMaterial.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jtfCodigoMaterialKeyPressed(evt);
            }
        });

        jcbNomeEstudantes.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jcbNomeEstudantesKeyPressed(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(lblCodigoMaterial, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jtfCodigoMaterial, javax.swing.GroupLayout.PREFERRED_SIZE, 243, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                        .addComponent(lblNomeEstudantes, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(18, 18, 18)
                        .addComponent(jcbNomeEstudantes, javax.swing.GroupLayout.PREFERRED_SIZE, 243, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(167, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblCodigoMaterial)
                    .addComponent(jtfCodigoMaterial, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 48, Short.MAX_VALUE)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblNomeEstudantes)
                    .addComponent(jcbNomeEstudantes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(70, 70, 70))
        );

        jPanel6.setLayout(null);

        jcbNomeFuncionarios.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jcbNomeFuncionarios.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jcbNomeFuncionariosKeyPressed(evt);
            }
        });
        jPanel6.add(jcbNomeFuncionarios);
        jcbNomeFuncionarios.setBounds(180, 10, 240, 30);

        lblNomeFuncionarios.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        lblNomeFuncionarios.setText("Nome Func.");
        jPanel6.add(lblNomeFuncionarios);
        lblNomeFuncionarios.setBounds(40, 10, 120, 22);

        lblMaterialRequisitado.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        lblMaterialRequisitado.setText("Material Req.");
        jPanel6.add(lblMaterialRequisitado);
        lblMaterialRequisitado.setBounds(40, 80, 120, 22);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, 512, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 13, Short.MAX_VALUE))
            .addComponent(jPanel6, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jPanel3.setLayout(new java.awt.BorderLayout());

        tabela.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Codigo Material", "Nome Estudante", "Nome Funcionario", "Material Requisitado", "Data"
            }
        ));
        tabela.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                tabelaAncestorAdded(evt);
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });
        tabela.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabelaMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tabela);

        jPanel3.add(jScrollPane2, java.awt.BorderLayout.CENTER);

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));

        jbtGravar.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jbtGravar.setText("Gravar");
        jbtGravar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtGravarActionPerformed(evt);
            }
        });
        jbtGravar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jbtGravarKeyPressed(evt);
            }
        });
        jPanel4.add(jbtGravar);

        jbtActualizar.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jbtActualizar.setText("Actualizar");
        jbtActualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtActualizarActionPerformed(evt);
            }
        });
        jPanel4.add(jbtActualizar);

        jbtRemover.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jbtRemover.setText("Remover");
        jbtRemover.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtRemoverActionPerformed(evt);
            }
        });
        jPanel4.add(jbtRemover);

        jbrPesquisar.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jbrPesquisar.setText("Pesquisar");
        jbrPesquisar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbrPesquisarActionPerformed(evt);
            }
        });
        jPanel4.add(jbrPesquisar);

        jbtLimpar.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jbtLimpar.setText("Limpar");
        jbtLimpar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtLimparActionPerformed(evt);
            }
        });
        jPanel4.add(jbtLimpar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, 190, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents


    private void jbtLimparActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtLimparActionPerformed
        // TODO add your handling code here:

        jcbNomeEstudantes.setSelectedIndex(0);
        //   jcbMaterialRequisitado.setSelectedIndex(0);
        jtfCodigoMaterial.setText(null);
        jcbNomeFuncionarios.setSelectedIndex(0);
        readJTable();
    }//GEN-LAST:event_jbtLimparActionPerformed

    private void jcbNomeFuncionariosKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jcbNomeFuncionariosKeyPressed
        // TODO add your handling code here:
        if (evt.getKeyCode() == evt.VK_ENTER) {
            //    jcbMaterialRequisitado.requestFocus();
        }
    }//GEN-LAST:event_jcbNomeFuncionariosKeyPressed

    private void tabelaAncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_tabelaAncestorAdded
        // TODO add your handling code here:
    }//GEN-LAST:event_tabelaAncestorAdded

    private void jbtGravarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtGravarActionPerformed
        // TODO add your handling code here:
        RequisitarMaterial a = new RequisitarMaterial();
        RequisitarMaterialDAO estu = new RequisitarMaterialDAO();

        Estudante estudante = (Estudante) jcbNomeEstudantes.getSelectedItem();
        a.setNomeestudante(estudante);
        Funcionario funcionario = (Funcionario) jcbNomeFuncionarios.getSelectedItem();
        a.setNomefuncionario(funcionario);
//        Material material = (Material) jcbMaterialRequisitado.getSelectedItem();
//        a.setMaterialrequisitado(material);
        a.setCodigo(jtfCodigoMaterial.getText());
        a.setData(new Date());

        if (estu.gravar(a)) {
            JOptionPane.showMessageDialog(null, "O Material foi requisitado com sucesso");
            jtfCodigoMaterial.setText(null);
            jcbNomeFuncionarios.setSelectedIndex(0);
            jcbNomeFuncionarios.setSelectedIndex(0);
//            jcbMaterialRequisitado.setSelectedIndex(0);
        } else {
            JOptionPane.showMessageDialog(null, "O Material nao foi requisitado com sucesso");
        }

        readJTable();
    }//GEN-LAST:event_jbtGravarActionPerformed

    private void jbtActualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtActualizarActionPerformed
        // TODO add your handling code here:
        if (tabela.getSelectedRow() != -1) {
            RequisitarMaterial a = new RequisitarMaterial();

            RequisitarMaterialDAO estu = new RequisitarMaterialDAO();

            a.setCodigo(jtfCodigoMaterial.getText());
            a.setNomeestudante((Estudante) jcbNomeEstudantes.getSelectedItem());
            a.setNomefuncionario((Funcionario) jcbNomeFuncionarios.getSelectedItem());
            //a.setMaterialrequisitado((Material) jcbMaterialRequisitado.getSelectedItem());
            a.setData((Date) tabela.getValueAt(tabela.getSelectedRow(), 4));

            if (estu.atualizar(a)) {
                JOptionPane.showMessageDialog(null, "Actualizacao efectuada com sucesso");
            } else {
                JOptionPane.showMessageDialog(null, "Nao foi possivel actualizar!!!");
            }

            jtfCodigoMaterial.setText(null);
            jcbNomeFuncionarios.setSelectedIndex(0);
            jcbNomeFuncionarios.setSelectedIndex(0);
            //  jcbMaterialRequisitado.setSelectedIndex(0);

        }
    }//GEN-LAST:event_jbtActualizarActionPerformed

    private void jbtRemoverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtRemoverActionPerformed
        // TODO add your handling code here:
        if (tabela.getSelectedRow() != -1) {
            RequisitarMaterial a = new RequisitarMaterial();
            RequisitarMaterialDAO dau = new RequisitarMaterialDAO();

            String d = tabela.getValueAt(tabela.getSelectedRow(), 0)
                    .toString();
            a.setCodigo(d);
            dau.remover(a);

            JOptionPane.showMessageDialog(null,
                    "Removido com sucesso");
            readJTable();

        } else {
            JOptionPane.showMessageDialog(null,
                    "Selecione um registo para poder remover");
        }

    }//GEN-LAST:event_jbtRemoverActionPerformed

    private void jbrPesquisarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbrPesquisarActionPerformed
        // TODO add your handling code here:
        readJTable1();
    }//GEN-LAST:event_jbrPesquisarActionPerformed

    private void tabelaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabelaMouseClicked
        // TODO add your handling code here:
        if (tabela.getSelectedRow() != -1) {
            jcbNomeEstudantes.setSelectedItem(tabela.getValueAt(tabela.getSelectedRow(), 1).toString());
            jtfCodigoMaterial.setText(tabela.getValueAt(tabela.getSelectedRow(), 0).toString());
            jcbNomeFuncionarios.setSelectedItem(tabela.getValueAt(tabela.getSelectedRow(), 2).toString());
            //  jcbMaterialRequisitado.setSelectedItem(tabela.getValueAt(tabela.getSelectedRow(), 2).toString());

        }
    }//GEN-LAST:event_tabelaMouseClicked

    private void jPanel5AncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_jPanel5AncestorAdded
        // TODO add your handling code here:
    }//GEN-LAST:event_jPanel5AncestorAdded

    private void jtfCodigoMaterialActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtfCodigoMaterialActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtfCodigoMaterialActionPerformed

    private void jtfCodigoMaterialKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtfCodigoMaterialKeyPressed

        // TODO add your handling code here:
        if (evt.getKeyCode() == evt.VK_ENTER) {
            jcbNomeEstudantes.requestFocus();
        }
    }//GEN-LAST:event_jtfCodigoMaterialKeyPressed

    private void jbtGravarKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jbtGravarKeyPressed
        // TODO add your handling code here:

    }//GEN-LAST:event_jbtGravarKeyPressed

    private void lblNomeEstudantesKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_lblNomeEstudantesKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_lblNomeEstudantesKeyPressed

    private void jcbNomeEstudantesKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jcbNomeEstudantesKeyPressed
        // TODO add your handling code here:
        // TODO add your handling code here:
        if (evt.getKeyCode() == evt.VK_ENTER) {
            jcbNomeFuncionarios.requestFocus();
        }
    }//GEN-LAST:event_jcbNomeEstudantesKeyPressed

    public void adcionarFuncionario() {
        FuncionarioDAO dao = new FuncionarioDAO();
        for (Funcionario t : dao.consular()) {
            jcbNomeFuncionarios.addItem(t);
        }
    }
    
     public void adcionarEstudante() {
        EstudanteDAO dao = new EstudanteDAO();
        for (Estudante t : dao.consular()) {
            jcbNomeEstudantes.addItem(t);
        }
    }


    public void readJTable() {
        DefaultTableModel modelo1 = (DefaultTableModel) tabela.getModel();
        modelo1.setNumRows(0);
        RequisitarMaterialDAO dau = new RequisitarMaterialDAO();

        for (RequisitarMaterial a : dau.consultar()) {

            modelo1.addRow(new Object[]{a.getCodigo(), a.getNomeestudante(),
                a.getNomefuncionario(), a.getMaterialrequisitado(), a.getData()

            });

        }
    }

    public void readJTable1() {
        DefaultTableModel modelo1 = (DefaultTableModel) tabela.getModel();
        modelo1.setNumRows(0);
        RequisitarMaterialDAO dau = new RequisitarMaterialDAO();

        for (RequisitarMaterial a : dau.consultar()) {
            if (a.getCodigo().equalsIgnoreCase(jtfCodigoMaterial.getText())) {

                modelo1.addRow(new Object[]{a.getCodigo(), a.getNomeestudante(),
                    a.getNomefuncionario(), a.getMaterialrequisitado(), a.getData()

                });
            }
        }
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;

                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaRequisitarMaterial.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaRequisitarMaterial.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaRequisitarMaterial.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaRequisitarMaterial.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaRequisitarMaterial().setVisible(true);

            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JButton jbrPesquisar;
    private javax.swing.JButton jbtActualizar;
    private javax.swing.JButton jbtGravar;
    private javax.swing.JButton jbtLimpar;
    private javax.swing.JButton jbtRemover;
    private javax.swing.JComboBox<Estudante> jcbNomeEstudantes;
    private javax.swing.JComboBox<Funcionario> jcbNomeFuncionarios;
    private javax.swing.JTextField jtfCodigoMaterial;
    private javax.swing.JLabel lblCodigoMaterial;
    private javax.swing.JLabel lblMaterialRequisitado;
    private javax.swing.JLabel lblNomeEstudantes;
    private javax.swing.JLabel lblNomeFuncionarios;
    private javax.swing.JLabel lblRequisitarMaterial;
    private javax.swing.JTable tabela;
    // End of variables declaration//GEN-END:variables
}
