/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Visao;

import java.awt.Color;
import java.awt.Toolkit;

/**
 *
 * @author Tpc
 */
public class TelaPrincipal extends javax.swing.JFrame {

    /**
     * Creates new form TelaPrincipal
     */
    public TelaPrincipal() {
        initComponents();
        Toolkit tk=Toolkit.getDefaultToolkit();
                int xsize = (int) tk.getScreenSize().getWidth();
                int ysize = (int) tk.getScreenSize().getHeight();
         this.setSize(xsize,ysize);
    }

    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        PainelCentral = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jmMenu = new javax.swing.JMenuBar();
        jmRegistar = new javax.swing.JMenu();
        jmiEstudante = new javax.swing.JMenuItem();
        jmiFuncionarios = new javax.swing.JMenuItem();
        jmiMaterias = new javax.swing.JMenuItem();
        jmiComputadores = new javax.swing.JMenuItem();
        jmiDocentes = new javax.swing.JMenuItem();
        jmiSalaDocentes = new javax.swing.JMenuItem();
        jmMateriais = new javax.swing.JMenu();
        jmLaboratorios = new javax.swing.JMenu();
        jmEstatisticas = new javax.swing.JMenu();
        jmRelatorios = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("TELA DO ADMINISTRADOR");

        PainelCentral.setBackground(new java.awt.Color(0, 204, 51));
        PainelCentral.setPreferredSize(new java.awt.Dimension(900, 600));
        PainelCentral.setLayout(new javax.swing.BoxLayout(PainelCentral, javax.swing.BoxLayout.LINE_AXIS));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/881474[1].jpg"))); // NOI18N
        PainelCentral.add(jLabel1);

        getContentPane().add(PainelCentral, java.awt.BorderLayout.CENTER);

        jmMenu.setBackground(new java.awt.Color(255, 255, 255));
        jmMenu.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 1, true));
        jmMenu.setDoubleBuffered(true);
        jmMenu.setFocusCycleRoot(true);
        jmMenu.setFocusTraversalPolicyProvider(true);

        jmRegistar.setText("Registar");
        jmRegistar.setFont(new java.awt.Font("DialogInput", 1, 18)); // NOI18N
        jmRegistar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jmRegistarMouseEntered(evt);
            }
        });

        jmiEstudante.setFont(new java.awt.Font("DialogInput", 0, 18)); // NOI18N
        jmiEstudante.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/user-icon.png"))); // NOI18N
        jmiEstudante.setText("Estudantes");
        jmiEstudante.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiEstudanteActionPerformed(evt);
            }
        });
        jmRegistar.add(jmiEstudante);

        jmiFuncionarios.setFont(new java.awt.Font("DialogInput", 0, 18)); // NOI18N
        jmiFuncionarios.setText("Funcionários");
        jmiFuncionarios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiFuncionariosActionPerformed(evt);
            }
        });
        jmRegistar.add(jmiFuncionarios);

        jmiMaterias.setFont(new java.awt.Font("DialogInput", 0, 18)); // NOI18N
        jmiMaterias.setText("Materiais");
        jmiMaterias.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiMateriasActionPerformed(evt);
            }
        });
        jmRegistar.add(jmiMaterias);

        jmiComputadores.setFont(new java.awt.Font("DialogInput", 0, 18)); // NOI18N
        jmiComputadores.setText("Computadores");
        jmiComputadores.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiComputadoresActionPerformed(evt);
            }
        });
        jmRegistar.add(jmiComputadores);

        jmiDocentes.setFont(new java.awt.Font("DialogInput", 0, 18)); // NOI18N
        jmiDocentes.setText("Docentes");
        jmiDocentes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiDocentesActionPerformed(evt);
            }
        });
        jmRegistar.add(jmiDocentes);

        jmiSalaDocentes.setFont(new java.awt.Font("DialogInput", 0, 18)); // NOI18N
        jmiSalaDocentes.setText("Salas dos Docentes");
        jmRegistar.add(jmiSalaDocentes);

        jmMenu.add(jmRegistar);

        jmMateriais.setText("Matériais");
        jmMateriais.setFont(new java.awt.Font("DialogInput", 1, 18)); // NOI18N
        jmMenu.add(jmMateriais);

        jmLaboratorios.setText("Laboratórios");
        jmLaboratorios.setFont(new java.awt.Font("DialogInput", 1, 18)); // NOI18N
        jmMenu.add(jmLaboratorios);

        jmEstatisticas.setText("Estatísticas");
        jmEstatisticas.setFont(new java.awt.Font("DialogInput", 1, 18)); // NOI18N
        jmMenu.add(jmEstatisticas);

        jmRelatorios.setBackground(new java.awt.Color(255, 255, 255));
        jmRelatorios.setText("Relatórios");
        jmRelatorios.setFont(new java.awt.Font("DialogInput", 1, 18)); // NOI18N
        jmMenu.add(jmRelatorios);

        setJMenuBar(jmMenu);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jmiEstudanteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiEstudanteActionPerformed
        // TODO add your handling code here:
        RegistarEstudant r = new RegistarEstudant();
        r.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jmiEstudanteActionPerformed

    private void jmiComputadoresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiComputadoresActionPerformed
        // TODO add your handling code here:
        new RegistarComputador().setVisible(true);
    }//GEN-LAST:event_jmiComputadoresActionPerformed

    private void jmiDocentesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiDocentesActionPerformed
        // TODO add your handling code here:
        new RegistarDocente().setVisible(true);
    }//GEN-LAST:event_jmiDocentesActionPerformed

    private void jmRegistarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jmRegistarMouseEntered
        // TODO add your handling code here:
       jmiEstudante.setVisible(true);
       jmiDocentes.setVisible(true);
       jmiComputadores.setVisible(true);
       jmiFuncionarios.setVisible(true);
       jmiSalaDocentes.setVisible(true);
       jmiMaterias.setVisible(true);
    }//GEN-LAST:event_jmRegistarMouseEntered

    private void jmiFuncionariosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiFuncionariosActionPerformed
        // TODO add your handling code here:
        new RegistarFuncionario().setVisible(true);
    }//GEN-LAST:event_jmiFuncionariosActionPerformed

    private void jmiMateriasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiMateriasActionPerformed
        // TODO add your handling code here:
        new RegistarMaterial().setVisible(true);
    }//GEN-LAST:event_jmiMateriasActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel PainelCentral;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JMenu jmEstatisticas;
    private javax.swing.JMenu jmLaboratorios;
    private javax.swing.JMenu jmMateriais;
    private javax.swing.JMenuBar jmMenu;
    private javax.swing.JMenu jmRegistar;
    private javax.swing.JMenu jmRelatorios;
    private javax.swing.JMenuItem jmiComputadores;
    private javax.swing.JMenuItem jmiDocentes;
    private javax.swing.JMenuItem jmiEstudante;
    private javax.swing.JMenuItem jmiFuncionarios;
    private javax.swing.JMenuItem jmiMaterias;
    private javax.swing.JMenuItem jmiSalaDocentes;
    // End of variables declaration//GEN-END:variables
}
